package:
  name: roq-api
  version: {{ GIT_DESCRIBE_TAG }}

source:
  git_url: ..

build:
  skip: true  # [not unix]
  number: {{ ROQ_BUILD_NUMBER if ROQ_BUILD_NUMBER is defined else GIT_DESCRIBE_NUMBER }}
  script_env:
    - ROQ_BUILD_NUMBER
    - ROQ_BUILD_TYPE
  run_exports:
    strong:
      - {{ pin_subpackage('roq-api', max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - clangdev
    - cmake
    - doxygen
    - flatbuffers
    - make
  host:
    - abseil-cpp
    - fmt
    - catch2  # [linux]
    - roq-oss-catch2  # [osx]
    - roq-oss-magic_enum
    - roq-oss-range-v3

about:
  home: https://roq-trading.com
  doc_url: https://roq-trading.com/docs
  dev_url: https://github.com/roq-trading
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Roq API
